name: Deploy React Client
on:
  push:
    branches: [main]
    paths:
      - 'client/**' # Only run if files in the client folder change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Install and Build 🔧
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/dist # The folder the action should deploy
          branch: gh-pages    # The branch the action should push to